name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write  # IMPORTANT: This permission is required for trusted publishing

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/doc-firewall
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.1.7
    
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.1.0
      with:
        python-version: "3.10"
        
    - name: Install build dependencies
      run: python -m pip install --require-hashes -r scripts/requirements-build.txt
      
    - name: Build distribution
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@ec4db0b4ddc65acdf4bff5fa45ac92d78b56bdf0 # v1.9.0